"name": "image-to-video-generator",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "@ffmpeg/ffmpeg": "^0.10.0",
    "file-saver": "^2.0.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build"
  }import React, { useState, useEffect } from 'react';
import { useDropzone } from 'react-dropzone';
import { createFFmpeg, fetchFile } from '@ffmpeg/ffmpeg';
import { saveAs } from 'file-saver';

const ffmpeg = createFFmpeg({ log: true });

function App() {
  const [images, setImages] = useState([]);
  const [videoBlob, setVideoBlob] = useState(null);
  const [lastGeneratedUrl, setLastGeneratedUrl] = useState('');
  const [ageVerified, setAgeVerified] = useState(false);
  const [showAgeModal, setShowAgeModal] = useState(true);
  const [prompt, setPrompt] = useState('');
  const [styleEffect, setStyleEffect] = useState('none');
  const [videoType, setVideoType] = useState('realistic');
  const [isProcessing, setIsProcessing] = useState(false);
  const [regenerateTrigger, setRegenerateTrigger] = useState(0);

  // Dropzone setup
  const { getRootProps, getInputProps } = useDropzone({
    accept: 'image/*',
    onDrop: (acceptedFiles) => {
      setImages((prev) => [...prev, ...acceptedFiles]);
    },
  });

  // Age verification
  const verifyAge = () => {
    setAgeVerified(true);
    setShowAgeModal(false);
  };

  // Effect filters placeholder
  const getEffectFilter = () => {
    switch (styleEffect) {
      case 'fantasy':
        return 'vignette';
      case 'sci-fi':
        return 'lenscorrection';
      case 'horror':
        return 'cinemaScope';
      case 'none':
      default:
        return '';
    }
  };

  // Generate video
  const generateVideo = async () => {
    setIsProcessing(true);
    if (!ffmpeg.isLoaded()) await ffmpeg.load();

    try {
      ffmpeg.FS('unlink', 'output.mp4');
    } catch(_) {}

    // Write images to ffmpeg FS
    for (let i = 0; i < images.length; i++) {
      ffmpeg.FS('writeFile', `img${i}.jpg`, await fetchFile(images[i]));
    }

    // Prepare input args with duration
    const inputArgs = [];
    const durationPerImage = 30 / images.length; // seconds
    for (let i = 0; i < images.length; i++) {
      inputArgs.push('-loop', '1', '-t', `${durationPerImage}`, '-i', `img${i}.jpg`);
    }

    // Effect filter (placeholder)
    const effectFilter = getEffectFilter();

    try {
      await ffmpeg.run(
        ...inputArgs,
        '-filter_complex', effectFilter,
        '-c:v', 'libx264',
        '-t', '30',
        '-pix_fmt', 'yuv420p',
        'output.mp4'
      );

      const data = ffmpeg.FS('readFile', 'output.mp4');
      const url = URL.createObjectURL(new Blob([data.buffer], { type: 'video/mp4' }));
      setVideoBlob(new Blob([data.buffer], { type: 'video/mp4' }));
      setLastGeneratedUrl(url);
    } catch (err) {
      console.error('Error generating video:', err);
    }
    setIsProcessing(false);
  };

  // Re-generate video
  const regenerateVideo = () => {
    setRegenerateTrigger(prev => prev + 1);
    generateVideo();
  };

  // Auto regenerate on trigger change
  useEffect(() => {
    if (images.length > 0 && ageVerified) {
      generateVideo();
    }
  }, [regenerateTrigger]);

  // Save video
  const saveVideoToDevice = () => {
    if (videoBlob) saveAs(videoBlob, 'generated_video.mp4');
  };

  // UI modal for age verification
  if (showAgeModal) {
    return (
      <div className="modal">
        <div className="modal-content">
          <h2>Are you 18 or older?</h2>
          <button onClick={verifyAge}>Yes, I am 18+</button>
        </div>
        <style jsx>{`
          .modal {
            position: fixed; top: 0; left: 0; right: 0; bottom: 0;
            background: rgba(0,0,0,0.8); display: flex; justify-content: center; align-items: center;
          }
          .modal-content {
            background: #fff; padding: 20px; border-radius: 8px; text-align: center;
          }
        `}</style>
      </div>
    );
  }

  return (
    <div className="app-container">
      <h1>Unfiltered Image-to-Video Generator</h1>
      
      {/* Prompt input */}
      <div className="section">
        <textarea
          placeholder="Enter your prompt (optional)..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
        />
      </div>

      {/* Style selection */}
      <div className="section">
        <label>Visual Style:</label>
        <select onChange={(e) => setStyleEffect(e.target.value)} value={styleEffect}>
          <option value="none">None</option>
          <option value="fantasy">Fantasy</option>
          <option value="sci-fi">Sci-Fi</option>
          <option value="horror">Horror</option>
          <option value="realistic">Realistic</option>
          <option value="fictional">Fictional</option>
        </select>
      </div>

      {/* Upload images */}
      <div {...getRootProps()} className="dropzone">
        <input {...getInputProps()} />
        <p>Drop unfiltered images or click to select</p>
      </div>

      {/* List images */}
      <ul>
        {images.map((file, index) => (
          <li key={index}>{file.name}</li>
        ))}
      </ul>

      {/* Generate / Regenerate buttons */}
      <div className="buttons">
        <button onClick={generateVideo} disabled={isProcessing || images.length === 0}>
          {isProcessing ? 'Processing...' : 'Generate 30s Video'}
        </button>
        {lastGeneratedUrl && (
          <>
            <video src={lastGeneratedUrl} controls width="100%" style={{ marginTop: '10px' }} />
            <div className="download-buttons">
              <button onClick={saveVideoToDevice}>Save to Device</button>
              <button onClick={regenerateVideo}>Regenerate</button>
            </div>
          </>
        )}
      </div>

      {/* Styling */}
      <style jsx>{`
        .app-container {
          max-width: 600px; margin: auto; padding: 10px; font-family: Arial, sans-serif;
        }
        h1 {
          text-align: center; margin-bottom: 20px;
        }
        .section {
          margin-bottom: 15px;
        }
        textarea {
          width: 100%; height: 80px; padding: 5px;
        }
        select {
          width: 100%; padding: 5px;
        }
        .dropzone {
          border: 2px dashed #999; padding: 20px; text-align: center; margin-bottom: 10px; cursor: pointer;
        }
        ul {
          list-style: none; padding-left: 0;
        }
        li {
          margin: 5px 0;
        }
        .buttons {
          display: flex; flex-direction: column; gap: 10px; margin-top: 20px;
        }
        .download-buttons {
          display: flex; gap: 10px; margin-top: 10px;
        }
        button {
          padding: 10px; cursor: pointer; width: 100%;
        }
      `}</style>
    </div>
  );
}

export default App;
